[package]
name = "MakeConfigTool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
autoaes ={path="../autoaes"}
fltk = "1.3.4"